<?php

namespace App\Filament\Resources\Participants\Schemas;

use Filament\Infolists\Components\IconEntry;
use Filament\Infolists\Components\TextEntry;
use Filament\Schemas\Schema;

class ParticipantInfolist
{
    public static function configure(Schema $schema): Schema
    {
        return $schema
            ->components([
                TextEntry::make('user.name')
                    ->label('User')
                    ->placeholder('-'),
                TextEntry::make('firstName')
                    ->placeholder('-'),
                TextEntry::make('surname')
                    ->placeholder('-'),
                TextEntry::make('subjectPronoun')
                    ->placeholder('-'),
                TextEntry::make('objectPronoun')
                    ->placeholder('-'),
                TextEntry::make('email')
                    ->label('Email address')
                    ->placeholder('-'),
                TextEntry::make('telephone')
                    ->placeholder('-'),
                TextEntry::make('address')
                    ->placeholder('-')
                    ->columnSpanFull(),
                TextEntry::make('postcode')
                    ->placeholder('-'),
                TextEntry::make('quality')
                    ->placeholder('-'),
                TextEntry::make('eastings')
                    ->placeholder('-'),
                TextEntry::make('northings')
                    ->placeholder('-'),
                TextEntry::make('country')
                    ->placeholder('-'),
                TextEntry::make('nhs_ha')
                    ->placeholder('-'),
                TextEntry::make('longitude')
                    ->placeholder('-'),
                TextEntry::make('latitude')
                    ->placeholder('-'),
                TextEntry::make('european_electoral_region')
                    ->placeholder('-'),
                TextEntry::make('primary_care_trust')
                    ->placeholder('-'),
                TextEntry::make('region')
                    ->placeholder('-'),
                TextEntry::make('lsoa')
                    ->placeholder('-'),
                TextEntry::make('msoa')
                    ->placeholder('-'),
                TextEntry::make('incode')
                    ->placeholder('-'),
                TextEntry::make('outcode')
                    ->placeholder('-'),
                TextEntry::make('parliamentary_constituency')
                    ->placeholder('-'),
                TextEntry::make('parliamentary_constituency_2024')
                    ->placeholder('-'),
                TextEntry::make('admin_district')
                    ->placeholder('-'),
                TextEntry::make('parish')
                    ->placeholder('-'),
                TextEntry::make('admin_county')
                    ->placeholder('-'),
                TextEntry::make('date_of_introduction')
                    ->placeholder('-'),
                TextEntry::make('admin_ward')
                    ->placeholder('-'),
                TextEntry::make('ced')
                    ->placeholder('-'),
                TextEntry::make('ccg')
                    ->placeholder('-'),
                TextEntry::make('nuts')
                    ->placeholder('-'),
                TextEntry::make('pfa')
                    ->placeholder('-'),
                TextEntry::make('nhs_region')
                    ->placeholder('-'),
                TextEntry::make('ttwa')
                    ->placeholder('-'),
                TextEntry::make('national_park')
                    ->placeholder('-'),
                TextEntry::make('bua')
                    ->placeholder('-'),
                TextEntry::make('icb')
                    ->placeholder('-'),
                TextEntry::make('cancer_alliance')
                    ->placeholder('-'),
                TextEntry::make('lsoa11')
                    ->placeholder('-'),
                TextEntry::make('msoa11')
                    ->placeholder('-'),
                TextEntry::make('lsoa21')
                    ->placeholder('-'),
                TextEntry::make('msoa21')
                    ->placeholder('-'),
                TextEntry::make('oa21')
                    ->placeholder('-'),
                TextEntry::make('ruc11')
                    ->placeholder('-'),
                TextEntry::make('ruc21')
                    ->placeholder('-'),
                TextEntry::make('lep1')
                    ->placeholder('-'),
                TextEntry::make('lep2')
                    ->placeholder('-'),
                TextEntry::make('dob')
                    ->date()
                    ->placeholder('-'),
                IconEntry::make('emergencyConsent')
                    ->boolean()
                    ->placeholder('-'),
                TextEntry::make('emergencyFirstName')
                    ->placeholder('-'),
                TextEntry::make('emergencySurname')
                    ->placeholder('-'),
                TextEntry::make('emergencyRelationship')
                    ->placeholder('-'),
                TextEntry::make('emergencyTelephone')
                    ->placeholder('-'),
                TextEntry::make('referrerOther')
                    ->placeholder('-'),
                TextEntry::make('disabilities')
                    ->placeholder('-'),
                TextEntry::make('difficulties')
                    ->placeholder('-'),
                TextEntry::make('ethnicity')
                    ->placeholder('-'),
                TextEntry::make('gender')
                    ->placeholder('-'),
                TextEntry::make('age')
                    ->placeholder('-'),
                IconEntry::make('declaration')
                    ->boolean()
                    ->placeholder('-'),
                IconEntry::make('surveys')
                    ->boolean()
                    ->placeholder('-'),
                TextEntry::make('created_at')
                    ->dateTime()
                    ->placeholder('-'),
                TextEntry::make('updated_at')
                    ->dateTime()
                    ->placeholder('-'),
            ]);
    }
}
